name: Deploy To Properia Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Kintana properia-dev subdomain
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_KINTANA_HOST }}
          username: ${{ secrets.SSH_KINTANA_USERNAME }}
          password: ${{ secrets.SSH_KINTANA_PASSWORD }}
          script: |
            cd /home/kintanat/domains/properia-dev.kintana-technology.com/public_html
            ./scripts/deploy_develop.sh